import { archiveDate, deployment, recordedNetwork, story, testnetContractUrl } from "./data";
import { Icon } from "./icons";

export function Developers() {
  return <div className="ct-page ct-developers"><div className="ct-page-intro"><h1>A precise record.<br />An inspectable contract.</h1><p>ClueTide links evidence commitments, version history and review decisions through a small registry on BOT Chain.</p></div>
    <div className="ct-developer-grid"><section className="ct-panel"><h2>One version graph.</h2><ol className="ct-api-flow"><li><code>create_case</code><p>Register the first report’s manifest commitment.</p></li><li><code>add_review</code><p>Bind a review and decision to an exact report version.</p></li><li><code>append_version</code><p>Append a correction with the previous version as its parent.</p></li></ol><a className="ct-text-link" href={story.contract_url} target="_blank" rel="noreferrer">Inspect the deployed registry <Icon name="external" /></a></section>
    <section className="ct-network"><h2>Recorded network</h2><dl><div><dt>Network</dt><dd>{recordedNetwork.name}</dd></div><div><dt>Chain ID</dt><dd>{recordedNetwork.chainId}</dd></div><div><dt>RPC</dt><dd><a href={recordedNetwork.rpc} target="_blank" rel="noreferrer">{new URL(recordedNetwork.rpc).hostname}</a></dd></div><div><dt>Explorer</dt><dd><a href={recordedNetwork.explorer} target="_blank" rel="noreferrer">{new URL(recordedNetwork.explorer).hostname} <Icon name="external" /></a></dd></div><div><dt>Contract</dt><dd><a className="ct-mono" href={story.contract_url} target="_blank" rel="noreferrer">{story.contract_address}</a></dd></div>{deployment ? <div><dt>Deployment</dt><dd><a className="ct-mono" href={deployment.tx_url} target="_blank" rel="noreferrer">View verified deployment <Icon name="external" /></a></dd></div> : null}<div><dt>Archive date</dt><dd>{archiveDate}</dd></div></dl><p className="ct-adaptation">The recorded workflow contains two versions and one review from the same wallet. Each receipt and exact content commitment was verified at its recorded observation time.</p></section></div>
    <section className="ct-developer-scope"><h2>Verification, with a defined scope.</h2><div className="ct-scope-row"><h3>Evidence commitment</h3><p>The manifest commits to the four public content files. Canonical JSON and SHA-256 allow another client to inspect the exact artifact.</p></div><div className="ct-scope-row"><h3>Transaction readback</h3><p>The local service checks the original intent against the transaction, receipt, canonical block, deployed code, emitted event and contract getters.</p></div><div className="ct-scope-row"><h3>Human interpretation</h3><p>Content integrity supports review. The evidence still determines whether a claim is justified, whether a source is authentic and who independently reviewed it.</p></div></section>
    <div className="ct-developer-links"><a className="ct-button ct-outline" href="https://github.com/HNNUYUXUAN/cluetide-review/tree/BOT" target="_blank" rel="noreferrer">Source and setup <Icon name="external" /></a><a className="ct-text-link" href="#/verify">Inspect an evidence bundle <Icon name="arrow" /></a><a className="ct-text-link" href={testnetContractUrl} target="_blank" rel="noreferrer">Archived testnet contract · 968 <Icon name="external" /></a></div>
  </div>;
}
